### ISSUE TITLE
Add something to enable remote pair programming

### ISSUE THREAD

**Issue by aaronjensen** [substantial/atomfiles#9] opened 2015-07-09 17:28 UTC
https://atom.io/packages/atom-pair
or
https://atom.io/packages/motepair
maybe

but probably not: https://atom.io/packages/pair-programming

**Comment by a-b-r-o-w-n** [comment] 2015-07-14 16:05
Seems to be a duplicate of #29

**Closed as completed** 2015-07-14 16:05 UTC
